name: CI

on: [push]

jobs:
  tests1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: dir1/requirements.txt

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: pip install -r dir1/requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Test
      run: pip freeze

  tests2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: dir2/requirements.txt

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: pip install -r dir2/requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Test
      run: pip freeze
